title: Computational Climate Science Curriculum
description: Satellite Data and Models for Computational Climate or Agricultural Science

# remote_theme: arthur-e/cause-jekyll-template
# plugins:
#   - jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: ""
